name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.15+1
  url_launcher: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/line_all.jpeg
    - images/2.0x/line_all@2x.jpeg
    - images/3.0x/line_all@3x.jpeg
    - images/arrow_map_chengshi.png
    - images/2.0x/arrow_map_chengshi@2x.png
    - images/3.0x/arrow_map_chengshi@3x.png
    - images/icon_Sign_weixin.png
    - images/2.0x/icon_Sign_weixin@2x.png
    - images/3.0x/icon_Sign_weixin@3x.png
    - images/icon_Sign_qq.png
    - images/2.0x/icon_Sign_qq@2x.png
    - images/3.0x/icon_Sign_qq@3x.png
    - images/icon_Sign_pay.png
    - images/2.0x/icon_Sign_pay@2x.png
    - images/3.0x/icon_Sign_pay@3x.png
    - assets/bus.json
    - images/lable_buslist_tuijian.png
    - images/2.0x/lable_buslist_tuijian@2x.png
    - images/3.0x/lable_buslist_tuijian@3x.png
    - images/img_buslist_..png
    - images/2.0x/img_buslist_.@2x.png
    - images/3.0x/img_buslist_.@3x.png
    - images/img_buslist_kong.png
    - images/2.0x/img_buslist_kong@2x.png
    - images/3.0x/img_buslist_kong@3x.png
    - images/img_buslist_line.png
    - images/2.0x/img_buslist_line@2x.png
    - images/3.0x/img_buslist_line@3x.png
    - images/icon_orderlist_bus.png
    - images/2.0x/icon_orderlist_bus@2x.png
    - images/3.0x/icon_orderlist_bus@3x.png
    - images/icon_orderlist_note.png
    - images/2.0x/icon_orderlist_note@2x.png
    - images/3.0x/icon_orderlist_note@3x.png
    - images/icon_info.png
    - images/2.0x/icon_info@2x.png
    - images/3.0x/icon_info@3x.png
    - images/icon_sign_eye_close.png
    - images/2.0x/icon_sign_eye_close@2x.png
    - images/3.0x/icon_sign_eye_close@3x.png
    - images/icon_sign_eye.png
    - images/2.0x/icon_sign_eye@2x.png
    - images/3.0x/icon_sign_eye@3x.png
    - images/icon_sign_delete.png
    - images/2.0x/icon_sign_delete@2x.png
    - images/3.0x/icon_sign_delete@3x.png
    - images/icon_cfcz_buslist_sel.png
    - images/2.0x/icon_cfcz_buslist_sel@2x.png
    - images/3.0x/icon_cfcz_buslist_sel@3x.png
    - images/icon_cfcz_buslist.png
    - images/2.0x/icon_cfcz_buslist@2x.png
    - images/3.0x/icon_cfcz_buslist@3x.png
    - images/icon_ddcz_buslist_sel.png
    - images/2.0x/icon_ddcz_buslist_sel@2x.png
    - images/3.0x/icon_ddcz_buslist_sel@3x.png
    - images/icon_ddcz_buslist.png
    - images/2.0x/icon_ddcz_buslist@2x.png
    - images/3.0x/icon_ddcz_buslist@3x.png
    - images/icon_time_buslist_rest.png
    - images/2.0x/icon_time_buslist_rest@2x.png
    - images/3.0x/icon_time_buslist_rest@3x.png
    - images/icon_time_buslist_sel.png
    - images/2.0x/icon_time_buslist_sel@2x.png
    - images/3.0x/icon_time_buslist_sel@3x.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
